Controller:
  extensions:
    - SS_MinifiedResponseExtension
Page:
  extensions:
    - PublicationPage
Page_Controller:
  extensions:
    - PublicationPage_Controller
BlogPost:
  extensions:
    - BlogFieldExtension
SiteConfig:
  extensions:
    - SiteConfigExtension