Controller:
  extensions:
    - SS_MinifiedResponseExtension
Page:
  extensions:
    - PublicationPage
SiteConfig:
  extensions:
    - SiteConfigExtension
Blog:
  extensions:
    - WidgetPageExtension
BlogPost:
  extensions:
    - WidgetPageExtension