Controller:
  extensions:
    - SS_MinifiedResponseExtension
Page:
  extensions:
    - PublicationPage
BlogPost:
  extensions:
    - BlogFieldExtension
SiteConfig:
  extensions:
    - SiteConfigExtension