---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'tag': 'TagController'
    'author': 'AuthorController'
    'category': 'CategoryController'